package com.example.domain.commentary.dialogues

import com.example.domain.commentary.CommentaryDialogue
import com.example.domain.commentary.Commentator

data class DialogueTemplate(
    val id: String,
    val lines: List<CommentaryDialogue>,
    val minRuns: Int? = null,
    val maxRuns: Int? = null,
    val requiresChase: Boolean = false,
    val requiresHighPressure: Boolean = false,
    val requiresConsecutive: Boolean = false
)

object BallDialogues {

    // --- 1 RUN DIALOGUES (40 Short Variations, <= 1 sec) ---
    val ONE_RUN_TEMPLATES: List<DialogueTemplate> = listOf(
        DialogueTemplate("1R_01", listOf(CommentaryDialogue(Commentator.RAHUL, "एक रन!"))),
        DialogueTemplate("1R_02", listOf(CommentaryDialogue(Commentator.NEHA, "सिंगल चुराया!"))),
        DialogueTemplate("1R_03", listOf(CommentaryDialogue(Commentator.RAHUL, "एक रन आसानी से!"))),
        DialogueTemplate("1R_04", listOf(CommentaryDialogue(Commentator.NEHA, "स्ट्राइक रोटेट की!"))),
        DialogueTemplate("1R_05", listOf(CommentaryDialogue(Commentator.RAHUL, "हल्के हाथों से एक रन!"))),
        DialogueTemplate("1R_06", listOf(CommentaryDialogue(Commentator.NEHA, "सिर्फ एक रन मिला!"))),
        DialogueTemplate("1R_07", listOf(CommentaryDialogue(Commentator.RAHUL, "तेज़ सिंगल!"))),
        DialogueTemplate("1R_08", listOf(CommentaryDialogue(Commentator.NEHA, "एक रन पूरा!"))),
        DialogueTemplate("1R_09", listOf(CommentaryDialogue(Commentator.RAHUL, "गैप में ढकेला, एक रन!"))),
        DialogueTemplate("1R_10", listOf(CommentaryDialogue(Commentator.NEHA, "समझदारी भरा सिंगल!"))),
        DialogueTemplate("1R_11", listOf(CommentaryDialogue(Commentator.RAHUL, "एक रन खाते में!"))),
        DialogueTemplate("1R_12", listOf(CommentaryDialogue(Commentator.NEHA, "आसानी से एक रन!"))),
        DialogueTemplate("1R_13", listOf(CommentaryDialogue(Commentator.RAHUL, "सुरक्षित सिंगल!"))),
        DialogueTemplate("1R_14", listOf(CommentaryDialogue(Commentator.NEHA, "स्कोर आगे बढ़ाया!"))),
        DialogueTemplate("1R_15", listOf(CommentaryDialogue(Commentator.RAHUL, "एक रन और!"))),
        DialogueTemplate("1R_16", listOf(CommentaryDialogue(Commentator.NEHA, "स्ट्राइक बदली!"))),
        DialogueTemplate("1R_17", listOf(CommentaryDialogue(Commentator.RAHUL, "तेज़ रनिंग, एक रन!"))),
        DialogueTemplate("1R_18", listOf(CommentaryDialogue(Commentator.NEHA, "एक रन मिला बल्लेबाज़ को!"))),
        DialogueTemplate("1R_19", listOf(CommentaryDialogue(Commentator.RAHUL, "चतुराई से एक रन!"))),
        DialogueTemplate("1R_20", listOf(CommentaryDialogue(Commentator.NEHA, "धीमी गति, एक रन!"))),
        DialogueTemplate("1R_21", listOf(CommentaryDialogue(Commentator.RAHUL, "दिशा दी और सिंगल!"))),
        DialogueTemplate("1R_22", listOf(CommentaryDialogue(Commentator.NEHA, "कवर पर धकेला, एक रन!"))),
        DialogueTemplate("1R_23", listOf(CommentaryDialogue(Commentator.RAHUL, "पैड्स पर लगी, एक रन!"))),
        DialogueTemplate("1R_24", listOf(CommentaryDialogue(Commentator.NEHA, "मिड ऑन की तरफ सिंगल!"))),
        DialogueTemplate("1R_25", listOf(CommentaryDialogue(Commentator.RAHUL, "शॉर्ट सिंगल निकाला!"))),
        DialogueTemplate("1R_26", listOf(CommentaryDialogue(Commentator.NEHA, "एक रन और जुड़ा!"))),
        DialogueTemplate("1R_27", listOf(CommentaryDialogue(Commentator.RAHUL, "सिंगल से खाता आगे!"))),
        DialogueTemplate("1R_28", listOf(CommentaryDialogue(Commentator.NEHA, "एक रन का इज़ाफ़ा!"))),
        DialogueTemplate("1R_29", listOf(CommentaryDialogue(Commentator.RAHUL, "शाबाश, बढ़िया सिंगल!"))),
        DialogueTemplate("1R_30", listOf(CommentaryDialogue(Commentator.NEHA, "एक रन लेकर संतुष्ट!"))),
        DialogueTemplate("1R_31", listOf(CommentaryDialogue(Commentator.RAHUL, "दौड़कर एक रन पूरा!"))),
        DialogueTemplate("1R_32", listOf(CommentaryDialogue(Commentator.NEHA, "बल्लेबाज़ सुरक्षित, एक रन!"))),
        DialogueTemplate("1R_33", listOf(CommentaryDialogue(Commentator.RAHUL, "अच्छा तालमेल, एक रन!"))),
        DialogueTemplate("1R_34", listOf(CommentaryDialogue(Commentator.NEHA, "एक रन से काम चलाया!"))),
        DialogueTemplate("1R_35", listOf(CommentaryDialogue(Commentator.RAHUL, "कलाई का इस्तेमाल, सिंगल!"))),
        DialogueTemplate("1R_36", listOf(CommentaryDialogue(Commentator.NEHA, "एक रन मिला!"))),
        DialogueTemplate("1R_37", listOf(CommentaryDialogue(Commentator.RAHUL, "क्विक सिंगल!"))),
        DialogueTemplate("1R_38", listOf(CommentaryDialogue(Commentator.NEHA, "सटीक रनिंग, एक रन!"))),
        DialogueTemplate("1R_39", listOf(CommentaryDialogue(Commentator.RAHUL, "बढ़िया कॉल, एक रन!"))),
        DialogueTemplate("1R_40", listOf(CommentaryDialogue(Commentator.NEHA, "आसान सिंगल!")))
    )

    // --- 2 RUNS DIALOGUES (32 Short Variations, <= 1 sec) ---
    val TWO_RUNS_TEMPLATES: List<DialogueTemplate> = listOf(
        DialogueTemplate("2R_01", listOf(CommentaryDialogue(Commentator.RAHUL, "दो रन आसानी से!"))),
        DialogueTemplate("2R_02", listOf(CommentaryDialogue(Commentator.NEHA, "तेज़ दौड़, दो रन!"))),
        DialogueTemplate("2R_03", listOf(CommentaryDialogue(Commentator.RAHUL, "डबल निकाला!"))),
        DialogueTemplate("2R_04", listOf(CommentaryDialogue(Commentator.NEHA, "शानदार रनिंग, दो रन!"))),
        DialogueTemplate("2R_05", listOf(CommentaryDialogue(Commentator.RAHUL, "दो रन चुरा लिए!"))),
        DialogueTemplate("2R_06", listOf(CommentaryDialogue(Commentator.NEHA, "गैप में खेला, दो रन!"))),
        DialogueTemplate("2R_07", listOf(CommentaryDialogue(Commentator.RAHUL, "बढ़िया तालमेल, दो रन!"))),
        DialogueTemplate("2R_08", listOf(CommentaryDialogue(Commentator.NEHA, "दो रन पूरे किए!"))),
        DialogueTemplate("2R_09", listOf(CommentaryDialogue(Commentator.RAHUL, "कमाल की दौड़, दो रन!"))),
        DialogueTemplate("2R_10", listOf(CommentaryDialogue(Commentator.NEHA, "दो रन खाते में जुड़े!"))),
        DialogueTemplate("2R_11", listOf(CommentaryDialogue(Commentator.RAHUL, "डायरेक्ट थ्रो चूका, दो रन!"))),
        DialogueTemplate("2R_12", listOf(CommentaryDialogue(Commentator.NEHA, "तेज़ मुड़े, दो रन!"))),
        DialogueTemplate("2R_13", listOf(CommentaryDialogue(Commentator.RAHUL, "दो रन का इज़ाफ़ा!"))),
        DialogueTemplate("2R_14", listOf(CommentaryDialogue(Commentator.NEHA, "आसानी से डबल!"))),
        DialogueTemplate("2R_15", listOf(CommentaryDialogue(Commentator.RAHUL, "शानदार प्लेसमेंट, दो रन!"))),
        DialogueTemplate("2R_16", listOf(CommentaryDialogue(Commentator.NEHA, "स्वीपर कवर पर दो रन!"))),
        DialogueTemplate("2R_17", listOf(CommentaryDialogue(Commentator.RAHUL, "डीप में गेंद, दो रन!"))),
        DialogueTemplate("2R_18", listOf(CommentaryDialogue(Commentator.NEHA, "शाबाश, दो रन मिले!"))),
        DialogueTemplate("2R_19", listOf(CommentaryDialogue(Commentator.RAHUL, "दो रन हासिल किए!"))),
        DialogueTemplate("2R_20", listOf(CommentaryDialogue(Commentator.NEHA, "गेंदबाज़ हैरान, दो रन!"))),
        DialogueTemplate("2R_21", listOf(CommentaryDialogue(Commentator.RAHUL, "तेज़ गति, दो रन!"))),
        DialogueTemplate("2R_22", listOf(CommentaryDialogue(Commentator.NEHA, "समझदारी से दो रन!"))),
        DialogueTemplate("2R_23", listOf(CommentaryDialogue(Commentator.RAHUL, "दो रन और स्कोरबोर्ड पर!"))),
        DialogueTemplate("2R_24", listOf(CommentaryDialogue(Commentator.NEHA, "सुपर रनिंग, दो रन!"))),
        DialogueTemplate("2R_25", listOf(CommentaryDialogue(Commentator.RAHUL, "विकेटों के बीच तेज़ी, दो रन!"))),
        DialogueTemplate("2R_26", listOf(CommentaryDialogue(Commentator.NEHA, "दो रन बटोरे!"))),
        DialogueTemplate("2R_27", listOf(CommentaryDialogue(Commentator.RAHUL, "फील्डर दूर, दो रन!"))),
        DialogueTemplate("2R_28", listOf(CommentaryDialogue(Commentator.NEHA, "कंट्रोल शॉट, दो रन!"))),
        DialogueTemplate("2R_29", listOf(CommentaryDialogue(Commentator.RAHUL, "डबल मुकम्मल!"))),
        DialogueTemplate("2R_30", listOf(CommentaryDialogue(Commentator.NEHA, "दो रन का बेहतरीन फायदा!"))),
        DialogueTemplate("2R_31", listOf(CommentaryDialogue(Commentator.RAHUL, "कॉल यस, दो रन!"))),
        DialogueTemplate("2R_32", listOf(CommentaryDialogue(Commentator.NEHA, "दो रन पूरे!")))
    )

    // --- 3 RUNS DIALOGUES (32 Short Variations, <= 1 sec) ---
    val THREE_RUNS_TEMPLATES: List<DialogueTemplate> = listOf(
        DialogueTemplate("3R_01", listOf(CommentaryDialogue(Commentator.RAHUL, "तीन रन पूरे!"))),
        DialogueTemplate("3R_02", listOf(CommentaryDialogue(Commentator.NEHA, "लाजवाब रनिंग, तीन रन!"))),
        DialogueTemplate("3R_03", listOf(CommentaryDialogue(Commentator.RAHUL, "बड़ा मैदान, तीन रन!"))),
        DialogueTemplate("3R_04", listOf(CommentaryDialogue(Commentator.NEHA, "तीन रन दौड़कर लिए!"))),
        DialogueTemplate("3R_05", listOf(CommentaryDialogue(Commentator.RAHUL, "बाउंड्री से पहले रुकी, तीन रन!"))),
        DialogueTemplate("3R_06", listOf(CommentaryDialogue(Commentator.NEHA, "कमाल की फुर्ती, तीन रन!"))),
        DialogueTemplate("3R_07", listOf(CommentaryDialogue(Commentator.RAHUL, "तीन रन चुराए!"))),
        DialogueTemplate("3R_08", listOf(CommentaryDialogue(Commentator.NEHA, "सटीक तालमेल, तीन रन!"))),
        DialogueTemplate("3R_09", listOf(CommentaryDialogue(Commentator.RAHUL, "तीन रन का इज़ाफ़ा!"))),
        DialogueTemplate("3R_10", listOf(CommentaryDialogue(Commentator.NEHA, "खूबसूरत दौड़, तीन रन!"))),
        DialogueTemplate("3R_11", listOf(CommentaryDialogue(Commentator.RAHUL, "फील्डर ने रोका, तीन रन!"))),
        DialogueTemplate("3R_12", listOf(CommentaryDialogue(Commentator.NEHA, "तीन रन आसानी से!"))),
        DialogueTemplate("3R_13", listOf(CommentaryDialogue(Commentator.RAHUL, "तीन रन खाते में!"))),
        DialogueTemplate("3R_14", listOf(CommentaryDialogue(Commentator.NEHA, "तेज़ धावक, तीन रन!"))),
        DialogueTemplate("3R_15", listOf(CommentaryDialogue(Commentator.RAHUL, "शानदार प्रयास, तीन रन!"))),
        DialogueTemplate("3R_16", listOf(CommentaryDialogue(Commentator.NEHA, "शानदार रनिंग, तीन रन!"))),
        DialogueTemplate("3R_17", listOf(CommentaryDialogue(Commentator.RAHUL, "तीन रन मिले बल्लेबाज़ को!"))),
        DialogueTemplate("3R_18", listOf(CommentaryDialogue(Commentator.NEHA, "तीन रन बटोरे!"))),
        DialogueTemplate("3R_19", listOf(CommentaryDialogue(Commentator.RAHUL, "अद्भुत दौड़, तीन रन!"))),
        DialogueTemplate("3R_20", listOf(CommentaryDialogue(Commentator.NEHA, "तीन रन मुकम्मल!"))),
        DialogueTemplate("3R_21", listOf(CommentaryDialogue(Commentator.RAHUL, "लंबी दौड़, तीन रन!"))),
        DialogueTemplate("3R_22", listOf(CommentaryDialogue(Commentator.NEHA, "बाउंड्री बचाई, तीन रन!"))),
        DialogueTemplate("3R_23", listOf(CommentaryDialogue(Commentator.RAHUL, "तीन रन सुरक्षित!"))),
        DialogueTemplate("3R_24", listOf(CommentaryDialogue(Commentator.NEHA, "शाबाश, तीन रन पूरे!"))),
        DialogueTemplate("3R_25", listOf(CommentaryDialogue(Commentator.RAHUL, "गहरी फील्डिंग, तीन रन!"))),
        DialogueTemplate("3R_26", listOf(CommentaryDialogue(Commentator.NEHA, "तीन रन जोड़े!"))),
        DialogueTemplate("3R_27", listOf(CommentaryDialogue(Commentator.RAHUL, "तीन रन की बड़ी बढ़त!"))),
        DialogueTemplate("3R_28", listOf(CommentaryDialogue(Commentator.NEHA, "तीन रन मिले!"))),
        DialogueTemplate("3R_29", listOf(CommentaryDialogue(Commentator.RAHUL, "तीन रन तेज़ी से!"))),
        DialogueTemplate("3R_30", listOf(CommentaryDialogue(Commentator.NEHA, "शानदार ट्रिपल!"))),
        DialogueTemplate("3R_31", listOf(CommentaryDialogue(Commentator.RAHUL, "तीन रन का फायदा!"))),
        DialogueTemplate("3R_32", listOf(CommentaryDialogue(Commentator.NEHA, "तीन रन दौड़ लिए!")))
    )

    // --- 4 RUNS / FOUR DIALOGUES (52 Short Variations, <= 1 sec) ---
    val FOUR_TEMPLATES: List<DialogueTemplate> = listOf(
        DialogueTemplate("4R_01", listOf(CommentaryDialogue(Commentator.RAHUL, "क्या शानदार चौका!"))),
        DialogueTemplate("4R_02", listOf(CommentaryDialogue(Commentator.NEHA, "सीधा बाउंड्री के बाहर!"))),
        DialogueTemplate("4R_03", listOf(CommentaryDialogue(Commentator.RAHUL, "चार रन, गोली की रफ्तार!"))),
        DialogueTemplate("4R_04", listOf(CommentaryDialogue(Commentator.NEHA, "खूबसूरत चौका!"))),
        DialogueTemplate("4R_05", listOf(CommentaryDialogue(Commentator.RAHUL, "गेंद सीमा रेखा पार, चार!"))),
        DialogueTemplate("4R_06", listOf(CommentaryDialogue(Commentator.NEHA, "बेहतरीन शॉट, चार रन!"))),
        DialogueTemplate("4R_07", listOf(CommentaryDialogue(Commentator.RAHUL, "रॉकेट की तरह चार रन!"))),
        DialogueTemplate("4R_08", listOf(CommentaryDialogue(Commentator.NEHA, "टाइमिंग लाजवाब, चौका!"))),
        DialogueTemplate("4R_09", listOf(CommentaryDialogue(Commentator.RAHUL, "नज़ाकत भरा चौका!"))),
        DialogueTemplate("4R_10", listOf(CommentaryDialogue(Commentator.NEHA, "कवर ड्राइव, चार रन!"))),
        DialogueTemplate("4R_11", listOf(CommentaryDialogue(Commentator.RAHUL, "गैप ढूंढा, चार रन!"))),
        DialogueTemplate("4R_12", listOf(CommentaryDialogue(Commentator.NEHA, "शानदार टाइमिंग, चौका!"))),
        DialogueTemplate("4R_13", listOf(CommentaryDialogue(Commentator.RAHUL, "फील्डर बेबस, चार रन!"))),
        DialogueTemplate("4R_14", listOf(CommentaryDialogue(Commentator.NEHA, "क्लासिक शॉट, चार रन!"))),
        DialogueTemplate("4R_15", listOf(CommentaryDialogue(Commentator.RAHUL, "बाउंड्री की झड़ी, चार!"))),
        DialogueTemplate("4R_16", listOf(CommentaryDialogue(Commentator.NEHA, "दमदार शॉट, चार रन!"))),
        DialogueTemplate("4R_17", listOf(CommentaryDialogue(Commentator.RAHUL, "करारा प्रहार, चार रन!"))),
        DialogueTemplate("4R_18", listOf(CommentaryDialogue(Commentator.NEHA, "क्या प्लेसमेंट है, चौका!"))),
        DialogueTemplate("4R_19", listOf(CommentaryDialogue(Commentator.RAHUL, "शानदार चौका निकाला!"))),
        DialogueTemplate("4R_20", listOf(CommentaryDialogue(Commentator.NEHA, "गेंदबाज़ पर हमला, चार!"))),
        DialogueTemplate("4R_21", listOf(CommentaryDialogue(Commentator.RAHUL, "पावरफुल शॉट, चार रन!"))),
        DialogueTemplate("4R_22", listOf(CommentaryDialogue(Commentator.NEHA, "स्ट्रेट ड्राइव, चार रन!"))),
        DialogueTemplate("4R_23", listOf(CommentaryDialogue(Commentator.RAHUL, "फ्लिक और चौका!"))),
        DialogueTemplate("4R_24", listOf(CommentaryDialogue(Commentator.NEHA, "पुल शॉट, चार रन!"))),
        DialogueTemplate("4R_25", listOf(CommentaryDialogue(Commentator.RAHUL, "कट शॉट, गेंद पार चार!"))),
        DialogueTemplate("4R_26", listOf(CommentaryDialogue(Commentator.NEHA, "चौका जड़ दिया!"))),
        DialogueTemplate("4R_27", listOf(CommentaryDialogue(Commentator.RAHUL, "गेंद गोली बनी, चार!"))),
        DialogueTemplate("4R_28", listOf(CommentaryDialogue(Commentator.NEHA, "सुपर शॉट, चार रन!"))),
        DialogueTemplate("4R_29", listOf(CommentaryDialogue(Commentator.RAHUL, "चौके से स्वागत!"))),
        DialogueTemplate("4R_30", listOf(CommentaryDialogue(Commentator.NEHA, "खूबसूरत बाउंड्री!"))),
        DialogueTemplate("4R_31", listOf(CommentaryDialogue(Commentator.RAHUL, "दबाव हटाया, चार रन!"))),
        DialogueTemplate("4R_32", listOf(CommentaryDialogue(Commentator.NEHA, "कमाल का स्ट्रोक, चार!"))),
        DialogueTemplate("4R_33", listOf(CommentaryDialogue(Commentator.RAHUL, "कलात्मक चौका!"))),
        DialogueTemplate("4R_34", listOf(CommentaryDialogue(Commentator.NEHA, "बाउंड्री के पार चार!"))),
        DialogueTemplate("4R_35", listOf(CommentaryDialogue(Commentator.RAHUL, "शानदार टाइमिंग, चार!"))),
        DialogueTemplate("4R_36", listOf(CommentaryDialogue(Commentator.NEHA, "गैप में गेंद, चार रन!"))),
        DialogueTemplate("4R_37", listOf(CommentaryDialogue(Commentator.RAHUL, "मास्टरक्लास शॉट, चार!"))),
        DialogueTemplate("4R_38", listOf(CommentaryDialogue(Commentator.NEHA, "चार रन का तोहफा!"))),
        DialogueTemplate("4R_39", listOf(CommentaryDialogue(Commentator.RAHUL, "मजबूत शॉट, चार रन!"))),
        DialogueTemplate("4R_40", listOf(CommentaryDialogue(Commentator.NEHA, "फील्डर को छकाया, चार!"))),
        DialogueTemplate("4R_41", listOf(CommentaryDialogue(Commentator.RAHUL, "स्वीप शॉट, चार रन!"))),
        DialogueTemplate("4R_42", listOf(CommentaryDialogue(Commentator.NEHA, "कमाल की हिट, चार!"))),
        DialogueTemplate("4R_43", listOf(CommentaryDialogue(Commentator.RAHUL, "चौके की गूंज!"))),
        DialogueTemplate("4R_44", listOf(CommentaryDialogue(Commentator.NEHA, "बाउंड्री! चार रन!"))),
        DialogueTemplate("4R_45", listOf(CommentaryDialogue(Commentator.RAHUL, "गेंद सीमा रेखा के बाहर!"))),
        DialogueTemplate("4R_46", listOf(CommentaryDialogue(Commentator.NEHA, "जबरदस्त चौका!"))),
        DialogueTemplate("4R_47", listOf(CommentaryDialogue(Commentator.RAHUL, "क्या स्ट्रोक है, चार रन!"))),
        DialogueTemplate("4R_48", listOf(CommentaryDialogue(Commentator.NEHA, "आतिशी चौका!"))),
        DialogueTemplate("4R_49", listOf(CommentaryDialogue(Commentator.RAHUL, "चौका और तालियां!"))),
        DialogueTemplate("4R_50", listOf(CommentaryDialogue(Commentator.NEHA, "अद्भुत चौका!"))),
        DialogueTemplate("4R_51", listOf(CommentaryDialogue(Commentator.RAHUL, "बिजली की गति, चार रन!"))),
        DialogueTemplate("4R_52", listOf(CommentaryDialogue(Commentator.NEHA, "चौका! चार रन!")))
    )

    // --- 6 RUNS / SIX DIALOGUES (52 Short Variations, <= 1 sec) ---
    val SIX_TEMPLATES: List<DialogueTemplate> = listOf(
        DialogueTemplate("6R_01", listOf(CommentaryDialogue(Commentator.RAHUL, "क्या कमाल का छक्का!"))),
        DialogueTemplate("6R_02", listOf(CommentaryDialogue(Commentator.NEHA, "गेंद सीधे दर्शकों में!"))),
        DialogueTemplate("6R_03", listOf(CommentaryDialogue(Commentator.RAHUL, "विशाल छक्का, छह रन!"))),
        DialogueTemplate("6R_04", listOf(CommentaryDialogue(Commentator.NEHA, "स्टेडियम पार, छह रन!"))),
        DialogueTemplate("6R_05", listOf(CommentaryDialogue(Commentator.RAHUL, "आसमानी छक्का!"))),
        DialogueTemplate("6R_06", listOf(CommentaryDialogue(Commentator.NEHA, "मॉन्स्टर सिक्स!"))),
        DialogueTemplate("6R_07", listOf(CommentaryDialogue(Commentator.RAHUL, "लंबा छक्का, छह रन!"))),
        DialogueTemplate("6R_08", listOf(CommentaryDialogue(Commentator.NEHA, "गेंद हवा में, छह रन!"))),
        DialogueTemplate("6R_09", listOf(CommentaryDialogue(Commentator.RAHUL, "शानदार छक्का जड़ दिया!"))),
        DialogueTemplate("6R_10", listOf(CommentaryDialogue(Commentator.NEHA, "सिक्सर! क्या शॉट है!"))),
        DialogueTemplate("6R_11", listOf(CommentaryDialogue(Commentator.RAHUL, "गेंद खो गई, छह रन!"))),
        DialogueTemplate("6R_12", listOf(CommentaryDialogue(Commentator.NEHA, "गगनचुंबी छक्का!"))),
        DialogueTemplate("6R_13", listOf(CommentaryDialogue(Commentator.RAHUL, "पावर-पैक्ड छक्का!"))),
        DialogueTemplate("6R_14", listOf(CommentaryDialogue(Commentator.NEHA, "छह रन, क्या टाइमिंग!"))),
        DialogueTemplate("6R_15", listOf(CommentaryDialogue(Commentator.RAHUL, "धमाकेदार छक्का!"))),
        DialogueTemplate("6R_16", listOf(CommentaryDialogue(Commentator.NEHA, "दर्शकों में गेंद, छह!"))),
        DialogueTemplate("6R_17", listOf(CommentaryDialogue(Commentator.RAHUL, "छक्के से स्वागत!"))),
        DialogueTemplate("6R_18", listOf(CommentaryDialogue(Commentator.NEHA, "कमाल का प्रहार, छह रन!"))),
        DialogueTemplate("6R_19", listOf(CommentaryDialogue(Commentator.RAHUL, "छक्का! क्या बात है!"))),
        DialogueTemplate("6R_20", listOf(CommentaryDialogue(Commentator.NEHA, "आसमान छूता छक्का!"))),
        DialogueTemplate("6R_21", listOf(CommentaryDialogue(Commentator.RAHUL, "रॉकेट शॉट, छह रन!"))),
        DialogueTemplate("6R_22", listOf(CommentaryDialogue(Commentator.NEHA, "विशाल प्रहार, छह रन!"))),
        DialogueTemplate("6R_23", listOf(CommentaryDialogue(Commentator.RAHUL, "गेंद छत पर, छह!"))),
        DialogueTemplate("6R_24", listOf(CommentaryDialogue(Commentator.NEHA, "छह रन, गेंदबाज़ स्तब्ध!"))),
        DialogueTemplate("6R_25", listOf(CommentaryDialogue(Commentator.RAHUL, "क्लासिक सिक्स!"))),
        DialogueTemplate("6R_26", listOf(CommentaryDialogue(Commentator.NEHA, "ज़बरदस्त हिट, छह रन!"))),
        DialogueTemplate("6R_27", listOf(CommentaryDialogue(Commentator.RAHUL, "छक्का और तूफान!"))),
        DialogueTemplate("6R_28", listOf(CommentaryDialogue(Commentator.NEHA, "खूबसूरत छक्का!"))),
        DialogueTemplate("6R_29", listOf(CommentaryDialogue(Commentator.RAHUL, "हेलीकॉप्टर शॉट, छह रन!"))),
        DialogueTemplate("6R_30", listOf(CommentaryDialogue(Commentator.NEHA, "पुल किया और छक्का!"))),
        DialogueTemplate("6R_31", listOf(CommentaryDialogue(Commentator.RAHUL, "लॉन्ग ऑन के ऊपर छह!"))),
        DialogueTemplate("6R_32", listOf(CommentaryDialogue(Commentator.NEHA, "मिडविकेट पार, छह रन!"))),
        DialogueTemplate("6R_33", listOf(CommentaryDialogue(Commentator.RAHUL, "सिक्स! क्या ताकत है!"))),
        DialogueTemplate("6R_34", listOf(CommentaryDialogue(Commentator.NEHA, "कवर के ऊपर से छह!"))),
        DialogueTemplate("6R_35", listOf(CommentaryDialogue(Commentator.RAHUL, "छक्के की गूंज!"))),
        DialogueTemplate("6R_36", listOf(CommentaryDialogue(Commentator.NEHA, "गेंद स्टेडियम से बाहर!"))),
        DialogueTemplate("6R_37", listOf(CommentaryDialogue(Commentator.RAHUL, "धुआंधार छक्का!"))),
        DialogueTemplate("6R_38", listOf(CommentaryDialogue(Commentator.NEHA, "छह रन, अद्भुत शॉट!"))),
        DialogueTemplate("6R_39", listOf(CommentaryDialogue(Commentator.RAHUL, "मैक्सिमम! छह रन!"))),
        DialogueTemplate("6R_40", listOf(CommentaryDialogue(Commentator.NEHA, "क्या कनेक्ट किया, छह!"))),
        DialogueTemplate("6R_41", listOf(CommentaryDialogue(Commentator.RAHUL, "छक्का! स्टेडियम झूमा!"))),
        DialogueTemplate("6R_42", listOf(CommentaryDialogue(Commentator.NEHA, "अविश्वसनीय छक्का!"))),
        DialogueTemplate("6R_43", listOf(CommentaryDialogue(Commentator.RAHUL, "छह रन का महाप्रहार!"))),
        DialogueTemplate("6R_44", listOf(CommentaryDialogue(Commentator.NEHA, "छह रन खाते में!"))),
        DialogueTemplate("6R_45", listOf(CommentaryDialogue(Commentator.RAHUL, "ताकत और टाइमिंग, छह!"))),
        DialogueTemplate("6R_46", listOf(CommentaryDialogue(Commentator.NEHA, "सुपर मैक्सिमम!"))),
        DialogueTemplate("6R_47", listOf(CommentaryDialogue(Commentator.RAHUL, "गेंद दर्शक दीर्घा में!"))),
        DialogueTemplate("6R_48", listOf(CommentaryDialogue(Commentator.NEHA, "छक्का और तालियां!"))),
        DialogueTemplate("6R_49", listOf(CommentaryDialogue(Commentator.RAHUL, "क्या छक्का मारा है!"))),
        DialogueTemplate("6R_50", listOf(CommentaryDialogue(Commentator.NEHA, "गेंद स्टैंड्स में, छह रन!"))),
        DialogueTemplate("6R_51", listOf(CommentaryDialogue(Commentator.RAHUL, "छक्का! छह रन!"))),
        DialogueTemplate("6R_52", listOf(CommentaryDialogue(Commentator.NEHA, "गेंदबाज़ पर प्रहार, छह!")))
    )

    // --- 0 RUN / DOT BALL DIALOGUES (45 Short Variations, <= 1 sec) ---
    val DOT_BALL_TEMPLATES: List<DialogueTemplate> = listOf(
        DialogueTemplate("DOT_01", listOf(CommentaryDialogue(Commentator.RAHUL, "शानदार डॉट बॉल!"))),
        DialogueTemplate("DOT_02", listOf(CommentaryDialogue(Commentator.NEHA, "गेंद खाली गई!"))),
        DialogueTemplate("DOT_03", listOf(CommentaryDialogue(Commentator.RAHUL, "बहुत बढ़िया गेंद!"))),
        DialogueTemplate("DOT_04", listOf(CommentaryDialogue(Commentator.NEHA, "कोई रन नहीं!"))),
        DialogueTemplate("DOT_05", listOf(CommentaryDialogue(Commentator.RAHUL, "बीट हुए बल्लेबाज़!"))),
        DialogueTemplate("DOT_06", listOf(CommentaryDialogue(Commentator.NEHA, "सटीक गेंदबाज़ी!"))),
        DialogueTemplate("DOT_07", listOf(CommentaryDialogue(Commentator.RAHUL, "डॉट बॉल, दबाव बढ़ा!"))),
        DialogueTemplate("DOT_08", listOf(CommentaryDialogue(Commentator.NEHA, "रन का कोई मौका नहीं!"))),
        DialogueTemplate("DOT_09", listOf(CommentaryDialogue(Commentator.RAHUL, "शानदार वापसी गेंदबाज़ की!"))),
        DialogueTemplate("DOT_10", listOf(CommentaryDialogue(Commentator.NEHA, "सीधे फील्डर के हाथ में!"))),
        DialogueTemplate("DOT_11", listOf(CommentaryDialogue(Commentator.RAHUL, "डिफेंस किया, कोई रन नहीं!"))),
        DialogueTemplate("DOT_12", listOf(CommentaryDialogue(Commentator.NEHA, "कमाल की यॉर्कर, डॉट!"))),
        DialogueTemplate("DOT_13", listOf(CommentaryDialogue(Commentator.RAHUL, "गेंदबाज़ हावी!"))),
        DialogueTemplate("DOT_14", listOf(CommentaryDialogue(Commentator.NEHA, "खाली गेंद!"))),
        DialogueTemplate("DOT_15", listOf(CommentaryDialogue(Commentator.RAHUL, "शानदार लेंथ, कोई रन नहीं!"))),
        DialogueTemplate("DOT_16", listOf(CommentaryDialogue(Commentator.NEHA, "बल्लेबाज़ खामोश!"))),
        DialogueTemplate("DOT_17", listOf(CommentaryDialogue(Commentator.RAHUL, "अच्छी लाइन, डॉट बॉल!"))),
        DialogueTemplate("DOT_18", listOf(CommentaryDialogue(Commentator.NEHA, "कोई रन नहीं मिला!"))),
        DialogueTemplate("DOT_19", listOf(CommentaryDialogue(Commentator.RAHUL, "चूक गए बल्लेबाज़!"))),
        DialogueTemplate("DOT_20", listOf(CommentaryDialogue(Commentator.NEHA, "गेंदबाज़ का दबदबा!"))),
        DialogueTemplate("DOT_21", listOf(CommentaryDialogue(Commentator.RAHUL, "शानदार डॉट डिलीवरी!"))),
        DialogueTemplate("DOT_22", listOf(CommentaryDialogue(Commentator.NEHA, "पूरी तरह बीट!"))),
        DialogueTemplate("DOT_23", listOf(CommentaryDialogue(Commentator.RAHUL, "गेंदबाज़ी में अनुशासन!"))),
        DialogueTemplate("DOT_24", listOf(CommentaryDialogue(Commentator.NEHA, "दबाव बनाती डॉट बॉल!"))),
        DialogueTemplate("DOT_25", listOf(CommentaryDialogue(Commentator.RAHUL, "कीमती डॉट गेंद!"))),
        DialogueTemplate("DOT_26", listOf(CommentaryDialogue(Commentator.NEHA, "रन रोकने में सफल!"))),
        DialogueTemplate("DOT_27", listOf(CommentaryDialogue(Commentator.RAHUL, "स्विंग हुई, कोई रन नहीं!"))),
        DialogueTemplate("DOT_28", listOf(CommentaryDialogue(Commentator.NEHA, "सटीक टप्पा, डॉट!"))),
        DialogueTemplate("DOT_29", listOf(CommentaryDialogue(Commentator.RAHUL, "बल्लेबाज़ असहाय!"))),
        DialogueTemplate("DOT_30", listOf(CommentaryDialogue(Commentator.NEHA, "गेंदबाज़ की तारीफ!"))),
        DialogueTemplate("DOT_31", listOf(CommentaryDialogue(Commentator.RAHUL, "रन नहीं मिलेगा!"))),
        DialogueTemplate("DOT_32", listOf(CommentaryDialogue(Commentator.NEHA, "सख्त पहरा, कोई रन नहीं!"))),
        DialogueTemplate("DOT_33", listOf(CommentaryDialogue(Commentator.RAHUL, "डॉट गेंद!"))),
        DialogueTemplate("DOT_34", listOf(CommentaryDialogue(Commentator.NEHA, "बल्लेबाज़ सोचने पर मजबूर!"))),
        DialogueTemplate("DOT_35", listOf(CommentaryDialogue(Commentator.RAHUL, "शानदार फील्डिंग, डॉट!"))),
        DialogueTemplate("DOT_36", listOf(CommentaryDialogue(Commentator.NEHA, "बांधकर रखा बल्लेबाज़ को!"))),
        DialogueTemplate("DOT_37", listOf(CommentaryDialogue(Commentator.RAHUL, "बिल्कुल खाली गेंद!"))),
        DialogueTemplate("DOT_38", listOf(CommentaryDialogue(Commentator.NEHA, "डॉट बॉल!"))),
        DialogueTemplate("DOT_39", listOf(CommentaryDialogue(Commentator.RAHUL, "कोई मौका नहीं रन का!"))),
        DialogueTemplate("DOT_40", listOf(CommentaryDialogue(Commentator.NEHA, "डॉट गेंद, बेहतरीन!"))),
        DialogueTemplate("DOT_41", listOf(CommentaryDialogue(Commentator.RAHUL, "शानदार डिफेंस, कोई रन नहीं!"))),
        DialogueTemplate("DOT_42", listOf(CommentaryDialogue(Commentator.NEHA, "रन बचा लिया फील्डर ने!"))),
        DialogueTemplate("DOT_43", listOf(CommentaryDialogue(Commentator.RAHUL, "डॉट डिलीवरी!"))),
        DialogueTemplate("DOT_44", listOf(CommentaryDialogue(Commentator.NEHA, "गेंदबाज़ आगे निकला!"))),
        DialogueTemplate("DOT_45", listOf(CommentaryDialogue(Commentator.RAHUL, "शून्य रन!")))
    )

    // --- 5 RUNS DIALOGUES (32 Short Variations, <= 1 sec) ---
    val FIVE_RUNS_TEMPLATES: List<DialogueTemplate> = listOf(
        DialogueTemplate("5R_01", listOf(CommentaryDialogue(Commentator.RAHUL, "पाँच रन!"))),
        DialogueTemplate("5R_02", listOf(CommentaryDialogue(Commentator.NEHA, "ओह, पाँच रन!"))),
        DialogueTemplate("5R_03", listOf(CommentaryDialogue(Commentator.RAHUL, "पूरे पाँच रन!"))),
        DialogueTemplate("5R_04", listOf(CommentaryDialogue(Commentator.NEHA, "क्या रनिंग है, पाँच रन!"))),
        DialogueTemplate("5R_05", listOf(CommentaryDialogue(Commentator.RAHUL, "पाँच रन मिल गए!"))),
        DialogueTemplate("5R_06", listOf(CommentaryDialogue(Commentator.NEHA, "पाँच रन शानदार!"))),
        DialogueTemplate("5R_07", listOf(CommentaryDialogue(Commentator.RAHUL, "बल्लेबाज़ ने पाँच ले लिए!"))),
        DialogueTemplate("5R_08", listOf(CommentaryDialogue(Commentator.NEHA, "वाह, पाँच रन!"))),
        DialogueTemplate("5R_09", listOf(CommentaryDialogue(Commentator.RAHUL, "दौड़कर पाँच रन बनाए!"))),
        DialogueTemplate("5R_10", listOf(CommentaryDialogue(Commentator.NEHA, "कमाल की दौड़, पाँच रन!"))),
        DialogueTemplate("5R_11", listOf(CommentaryDialogue(Commentator.RAHUL, "पाँच रन खाते में!"))),
        DialogueTemplate("5R_12", listOf(CommentaryDialogue(Commentator.NEHA, "अविश्वसनीय पाँच रन!"))),
        DialogueTemplate("5R_13", listOf(CommentaryDialogue(Commentator.RAHUL, "पाँच रन पूरे किए!"))),
        DialogueTemplate("5R_14", listOf(CommentaryDialogue(Commentator.NEHA, "लाजवाब रनिंग, पाँच रन!"))),
        DialogueTemplate("5R_15", listOf(CommentaryDialogue(Commentator.RAHUL, "पाँच रन चुरा लिए!"))),
        DialogueTemplate("5R_16", listOf(CommentaryDialogue(Commentator.NEHA, "पाँच रन का इज़ाफ़ा!"))),
        DialogueTemplate("5R_17", listOf(CommentaryDialogue(Commentator.RAHUL, "तेज़ दौड़, पाँच रन!"))),
        DialogueTemplate("5R_18", listOf(CommentaryDialogue(Commentator.NEHA, "पाँच रन जोड़ लिए!"))),
        DialogueTemplate("5R_19", listOf(CommentaryDialogue(Commentator.RAHUL, "क्या दौड़ लगाई, पाँच रन!"))),
        DialogueTemplate("5R_20", listOf(CommentaryDialogue(Commentator.NEHA, "शानदार पाँच रन!"))),
        DialogueTemplate("5R_21", listOf(CommentaryDialogue(Commentator.RAHUL, "पाँच रन बटोरे!"))),
        DialogueTemplate("5R_22", listOf(CommentaryDialogue(Commentator.NEHA, "धमाकेदार रनिंग, पाँच!"))),
        DialogueTemplate("5R_23", listOf(CommentaryDialogue(Commentator.RAHUL, "पाँच रन मुकम्मल!"))),
        DialogueTemplate("5R_24", listOf(CommentaryDialogue(Commentator.NEHA, "शाबाश, पाँच रन!"))),
        DialogueTemplate("5R_25", listOf(CommentaryDialogue(Commentator.RAHUL, "पाँच रन हासिल किए!"))),
        DialogueTemplate("5R_26", listOf(CommentaryDialogue(Commentator.NEHA, "अद्भुत फुर्ती, पाँच रन!"))),
        DialogueTemplate("5R_27", listOf(CommentaryDialogue(Commentator.RAHUL, "पाँच रन मिले बल्लेबाज़ को!"))),
        DialogueTemplate("5R_28", listOf(CommentaryDialogue(Commentator.NEHA, "सुपर दौड़, पाँच रन!"))),
        DialogueTemplate("5R_29", listOf(CommentaryDialogue(Commentator.RAHUL, "पाँच रन पूरे!"))),
        DialogueTemplate("5R_30", listOf(CommentaryDialogue(Commentator.NEHA, "कमाल के पाँच रन!"))),
        DialogueTemplate("5R_31", listOf(CommentaryDialogue(Commentator.RAHUL, "पाँच रन की बड़ी बढ़त!"))),
        DialogueTemplate("5R_32", listOf(CommentaryDialogue(Commentator.NEHA, "पाँच रन और!")))
    )
}
