package com.example.domain.commentary.dialogues

import com.example.domain.commentary.CommentaryDialogue
import com.example.domain.commentary.Commentator

object KnockoutDialogues {

    // --- SUPER OVER DIALOGUES (30 Short Variations, <= 1 sec) ---
    val SUPER_OVER_TEMPLATES: List<DialogueTemplate> = listOf(
        DialogueTemplate("SO_01", listOf(CommentaryDialogue(Commentator.RAHUL, "टाई हुआ! सुपर ओवर!"))),
        DialogueTemplate("SO_02", listOf(CommentaryDialogue(Commentator.NEHA, "सुपर ओवर का महामुकाबला!"))),
        DialogueTemplate("SO_03", listOf(CommentaryDialogue(Commentator.RAHUL, "अब सुपर ओवर में फैसला!"))),
        DialogueTemplate("SO_04", listOf(CommentaryDialogue(Commentator.NEHA, "छह गेंदों का सुपर ओवर!"))),
        DialogueTemplate("SO_05", listOf(CommentaryDialogue(Commentator.RAHUL, "सुपर ओवर का महासंग्राम!"))),
        DialogueTemplate("SO_06", listOf(CommentaryDialogue(Commentator.NEHA, "रोमांच की पराकाष्ठा!"))),
        DialogueTemplate("SO_07", listOf(CommentaryDialogue(Commentator.RAHUL, "सुपर ओवर! धड़कनें तेज!"))),
        DialogueTemplate("SO_08", listOf(CommentaryDialogue(Commentator.NEHA, "छह गेंदें तय करेंगी विजेता!"))),
        DialogueTemplate("SO_09", listOf(CommentaryDialogue(Commentator.RAHUL, "सुपर ओवर शुरू!"))),
        DialogueTemplate("SO_10", listOf(CommentaryDialogue(Commentator.NEHA, "सुपर ओवर का घमासान!"))),
        DialogueTemplate("SO_11", listOf(CommentaryDialogue(Commentator.RAHUL, "क्या मैच है! सुपर ओवर!"))),
        DialogueTemplate("SO_12", listOf(CommentaryDialogue(Commentator.NEHA, "सुपर ओवर में आर-पार!"))),
        DialogueTemplate("SO_13", listOf(CommentaryDialogue(Commentator.RAHUL, "सुपर ओवर का नॉकआउट!"))),
        DialogueTemplate("SO_14", listOf(CommentaryDialogue(Commentator.NEHA, "मैच टाई, सुपर ओवर!"))),
        DialogueTemplate("SO_15", listOf(CommentaryDialogue(Commentator.RAHUL, "सुपर ओवर! सांसें थमीं!"))),
        DialogueTemplate("SO_16", listOf(CommentaryDialogue(Commentator.NEHA, "सुपर ओवर की पहली गेंद!"))),
        DialogueTemplate("SO_17", listOf(CommentaryDialogue(Commentator.RAHUL, "छह गेंदों का असली टेस्ट!"))),
        DialogueTemplate("SO_18", listOf(CommentaryDialogue(Commentator.NEHA, "सुपर ओवर का हाई वोल्टेज ड्रामा!"))),
        DialogueTemplate("SO_19", listOf(CommentaryDialogue(Commentator.RAHUL, "सुपर ओवर! गलती की गुंजाइश नहीं!"))),
        DialogueTemplate("SO_20", listOf(CommentaryDialogue(Commentator.NEHA, "सुपर ओवर में अंतिम फैसला!"))),
        DialogueTemplate("SO_21", listOf(CommentaryDialogue(Commentator.RAHUL, "क्या थ्रिलर है, सुपर ओवर!"))),
        DialogueTemplate("SO_22", listOf(CommentaryDialogue(Commentator.NEHA, "सुपर ओवर की अग्निपरीक्षा!"))),
        DialogueTemplate("SO_23", listOf(CommentaryDialogue(Commentator.RAHUL, "सुपर ओवर! मैदान पर बिजली!"))),
        DialogueTemplate("SO_24", listOf(CommentaryDialogue(Commentator.NEHA, "सुपर ओवर में सब कुछ दांव पर!"))),
        DialogueTemplate("SO_25", listOf(CommentaryDialogue(Commentator.RAHUL, "सुपर ओवर की चुनौती!"))),
        DialogueTemplate("SO_26", listOf(CommentaryDialogue(Commentator.NEHA, "सुपर ओवर! इतिहास रचेगा!"))),
        DialogueTemplate("SO_27", listOf(CommentaryDialogue(Commentator.RAHUL, "रोमांचक सुपर ओवर!"))),
        DialogueTemplate("SO_28", listOf(CommentaryDialogue(Commentator.NEHA, "सुपर ओवर की घंटी बजी!"))),
        DialogueTemplate("SO_29", listOf(CommentaryDialogue(Commentator.RAHUL, "सुपर ओवर का खेल!"))),
        DialogueTemplate("SO_30", listOf(CommentaryDialogue(Commentator.NEHA, "सुपर ओवर! करो या मरो!")))
    )

    // --- SEMI-FINAL DIALOGUES (30 Short Variations, <= 1 sec) ---
    val SEMI_FINAL_TEMPLATES: List<DialogueTemplate> = listOf(
        DialogueTemplate("SF_01", listOf(CommentaryDialogue(Commentator.RAHUL, "सेमी-फाइनल का बड़ा मुकाबला!"))),
        DialogueTemplate("SF_02", listOf(CommentaryDialogue(Commentator.NEHA, "फाइनल का टिकट दांव पर!"))),
        DialogueTemplate("SF_03", listOf(CommentaryDialogue(Commentator.RAHUL, "सेमी-फाइनल का महासंग्राम!"))),
        DialogueTemplate("SF_04", listOf(CommentaryDialogue(Commentator.NEHA, "फाइनल में जाने की जंग!"))),
        DialogueTemplate("SF_05", listOf(CommentaryDialogue(Commentator.RAHUL, "सेमी-फाइनल की बड़ी जंग!"))),
        DialogueTemplate("SF_06", listOf(CommentaryDialogue(Commentator.NEHA, "सेमी-फाइनल में आर-पार!"))),
        DialogueTemplate("SF_07", listOf(CommentaryDialogue(Commentator.RAHUL, "फाइनल की दहलीज पर!"))),
        DialogueTemplate("SF_08", listOf(CommentaryDialogue(Commentator.NEHA, "सेमी-फाइनल का घमासान!"))),
        DialogueTemplate("SF_09", listOf(CommentaryDialogue(Commentator.RAHUL, "सेमी-फाइनल का हाई वोल्टेज मैच!"))),
        DialogueTemplate("SF_10", listOf(CommentaryDialogue(Commentator.NEHA, "फाइनल का रास्ता यहीं से!"))),
        DialogueTemplate("SF_11", listOf(CommentaryDialogue(Commentator.RAHUL, "सेमी-फाइनल की अग्निपरीक्षा!"))),
        DialogueTemplate("SF_12", listOf(CommentaryDialogue(Commentator.NEHA, "सेमी-फाइनल में जीत जरूरी!"))),
        DialogueTemplate("SF_13", listOf(CommentaryDialogue(Commentator.RAHUL, "सेमी-फाइनल का दबाव!"))),
        DialogueTemplate("SF_14", listOf(CommentaryDialogue(Commentator.NEHA, "फाइनल में जगह पक्की करने की जंग!"))),
        DialogueTemplate("SF_15", listOf(CommentaryDialogue(Commentator.RAHUL, "सेमी-फाइनल का बड़ा दिन!"))),
        DialogueTemplate("SF_16", listOf(CommentaryDialogue(Commentator.NEHA, "सेमी-फाइनल में कदम रखा!"))),
        DialogueTemplate("SF_17", listOf(CommentaryDialogue(Commentator.RAHUL, "फाइनल के लिए करो या मरो!"))),
        DialogueTemplate("SF_18", listOf(CommentaryDialogue(Commentator.NEHA, "सेमी-फाइनल का मुकाबला शुरू!"))),
        DialogueTemplate("SF_19", listOf(CommentaryDialogue(Commentator.RAHUL, "सेमी-फाइनल की चुनौती!"))),
        DialogueTemplate("SF_20", listOf(CommentaryDialogue(Commentator.NEHA, "सेमी-फाइनल में इतिहास!"))),
        DialogueTemplate("SF_21", listOf(CommentaryDialogue(Commentator.RAHUL, "सेमी-फाइनल का रोमांच!"))),
        DialogueTemplate("SF_22", listOf(CommentaryDialogue(Commentator.NEHA, "फाइनल की रेस का सेमीफाइनल!"))),
        DialogueTemplate("SF_23", listOf(CommentaryDialogue(Commentator.RAHUL, "सेमी-फाइनल में जीत हासिल!"))),
        DialogueTemplate("SF_24", listOf(CommentaryDialogue(Commentator.NEHA, "फाइनल का टिकट कटाया!"))),
        DialogueTemplate("SF_25", listOf(CommentaryDialogue(Commentator.RAHUL, "सेमी-फाइनल की शानदार जीत!"))),
        DialogueTemplate("SF_26", listOf(CommentaryDialogue(Commentator.NEHA, "सीधे फाइनल में पहुंचे!"))),
        DialogueTemplate("SF_27", listOf(CommentaryDialogue(Commentator.RAHUL, "फाइनल का रास्ता साफ!"))),
        DialogueTemplate("SF_28", listOf(CommentaryDialogue(Commentator.NEHA, "सेमी-फाइनल में फतेह!"))),
        DialogueTemplate("SF_29", listOf(CommentaryDialogue(Commentator.RAHUL, "फाइनल की तैयारी शुरू!"))),
        DialogueTemplate("SF_30", listOf(CommentaryDialogue(Commentator.NEHA, "फाइनल में धमाकेदार एंट्री!")))
    )

    // --- FINAL DIALOGUES (40 Short Variations, <= 1 sec) ---
    val FINAL_TEMPLATES: List<DialogueTemplate> = listOf(
        DialogueTemplate("FN_01", listOf(CommentaryDialogue(Commentator.RAHUL, "वर्ल्ड कप फाइनल का मुकाबला!"))),
        DialogueTemplate("FN_02", listOf(CommentaryDialogue(Commentator.NEHA, "ट्रॉफी की असली जंग!"))),
        DialogueTemplate("FN_03", listOf(CommentaryDialogue(Commentator.RAHUL, "फाइनल का महामुकाबला!"))),
        DialogueTemplate("FN_04", listOf(CommentaryDialogue(Commentator.NEHA, "आज बनेगा विश्व चैंपियन!"))),
        DialogueTemplate("FN_05", listOf(CommentaryDialogue(Commentator.RAHUL, "फाइनल का महासंग्राम!"))),
        DialogueTemplate("FN_06", listOf(CommentaryDialogue(Commentator.NEHA, "वर्ल्ड कप फाइनल का दिन!"))),
        DialogueTemplate("FN_07", listOf(CommentaryDialogue(Commentator.RAHUL, "ट्रॉफी किसके नाम होगी!"))),
        DialogueTemplate("FN_08", listOf(CommentaryDialogue(Commentator.NEHA, "फाइनल का ऐतिहासिक मैच!"))),
        DialogueTemplate("FN_09", listOf(CommentaryDialogue(Commentator.RAHUL, "दुनिया की नजरें फाइनल पर!"))),
        DialogueTemplate("FN_10", listOf(CommentaryDialogue(Commentator.NEHA, "वर्ल्ड कप ट्रॉफी दांव पर!"))),
        DialogueTemplate("FN_11", listOf(CommentaryDialogue(Commentator.RAHUL, "फाइनल की सबसे बड़ी लड़ाई!"))),
        DialogueTemplate("FN_12", listOf(CommentaryDialogue(Commentator.NEHA, "फाइनल का रोमांच चरम पर!"))),
        DialogueTemplate("FN_13", listOf(CommentaryDialogue(Commentator.RAHUL, "आज इतिहास लिखा जाएगा!"))),
        DialogueTemplate("FN_14", listOf(CommentaryDialogue(Commentator.NEHA, "वर्ल्ड कप फाइनल की शुरुआत!"))),
        DialogueTemplate("FN_15", listOf(CommentaryDialogue(Commentator.RAHUL, "फाइनल में आमने-सामने!"))),
        DialogueTemplate("FN_16", listOf(CommentaryDialogue(Commentator.NEHA, "फाइनल का महायुद्ध!"))),
        DialogueTemplate("FN_17", listOf(CommentaryDialogue(Commentator.RAHUL, "ट्रॉफी उठाने की जंग!"))),
        DialogueTemplate("FN_18", listOf(CommentaryDialogue(Commentator.NEHA, "फाइनल में हर गेंद कीमती!"))),
        DialogueTemplate("FN_19", listOf(CommentaryDialogue(Commentator.RAHUL, "वर्ल्ड कप का सबसे बड़ा मैच!"))),
        DialogueTemplate("FN_20", listOf(CommentaryDialogue(Commentator.NEHA, "फाइनल में कोई ढील नहीं!"))),
        DialogueTemplate("FN_21", listOf(CommentaryDialogue(Commentator.RAHUL, "आज का दिन यादगार होगा!"))),
        DialogueTemplate("FN_22", listOf(CommentaryDialogue(Commentator.NEHA, "फाइनल का ताज किसके सिर!"))),
        DialogueTemplate("FN_23", listOf(CommentaryDialogue(Commentator.RAHUL, "फाइनल का घमासान जारी!"))),
        DialogueTemplate("FN_24", listOf(CommentaryDialogue(Commentator.NEHA, "वर्ल्ड कप जीतने का सपना!"))),
        DialogueTemplate("FN_25", listOf(CommentaryDialogue(Commentator.RAHUL, "फाइनल की असली परीक्षा!"))),
        DialogueTemplate("FN_26", listOf(CommentaryDialogue(Commentator.NEHA, "फाइनल में धड़कनें तेज!"))),
        DialogueTemplate("FN_27", listOf(CommentaryDialogue(Commentator.RAHUL, "स्टेडियम में फाइनल का शोर!"))),
        DialogueTemplate("FN_28", listOf(CommentaryDialogue(Commentator.NEHA, "फाइनल की बड़ी टक्कर!"))),
        DialogueTemplate("FN_29", listOf(CommentaryDialogue(Commentator.RAHUL, "वर्ल्ड कप फाइनल का जादू!"))),
        DialogueTemplate("FN_30", listOf(CommentaryDialogue(Commentator.NEHA, "फाइनल में जबरदस्त मुकाबला!"))),
        DialogueTemplate("FN_31", listOf(CommentaryDialogue(Commentator.RAHUL, "फाइनल की पहली गेंद!"))),
        DialogueTemplate("FN_32", listOf(CommentaryDialogue(Commentator.NEHA, "ट्रॉफी का अंतिम चरण!"))),
        DialogueTemplate("FN_33", listOf(CommentaryDialogue(Commentator.RAHUL, "फाइनल में सब दांव पर!"))),
        DialogueTemplate("FN_34", listOf(CommentaryDialogue(Commentator.NEHA, "वर्ल्ड कप का सुनहरा पल!"))),
        DialogueTemplate("FN_35", listOf(CommentaryDialogue(Commentator.RAHUL, "फाइनल की कांटे की टक्कर!"))),
        DialogueTemplate("FN_36", listOf(CommentaryDialogue(Commentator.NEHA, "फाइनल में चैंपियन बनने की दौड़!"))),
        DialogueTemplate("FN_37", listOf(CommentaryDialogue(Commentator.RAHUL, "फाइनल का महामुकाबला!"))),
        DialogueTemplate("FN_38", listOf(CommentaryDialogue(Commentator.NEHA, "फाइनल का शानदार माहौल!"))),
        DialogueTemplate("FN_39", listOf(CommentaryDialogue(Commentator.RAHUL, "ट्रॉफी की जंग चरम पर!"))),
        DialogueTemplate("FN_40", listOf(CommentaryDialogue(Commentator.NEHA, "वर्ल्ड कप फाइनल!")))
    )

    // --- CHAMPION DIALOGUES (40 Short Variations, <= 1 sec) ---
    val CHAMPION_TEMPLATES: List<DialogueTemplate> = listOf(
        DialogueTemplate("CHP_01", listOf(CommentaryDialogue(Commentator.RAHUL, "विश्व चैंपियन बन गए!"))),
        DialogueTemplate("CHP_02", listOf(CommentaryDialogue(Commentator.NEHA, "वर्ल्ड कप जीत लिया!"))),
        DialogueTemplate("CHP_03", listOf(CommentaryDialogue(Commentator.RAHUL, "इतिहास रचा, चैंपियन बने!"))),
        DialogueTemplate("CHP_04", listOf(CommentaryDialogue(Commentator.NEHA, "ट्रॉफी अपने नाम कर ली!"))),
        DialogueTemplate("CHP_05", listOf(CommentaryDialogue(Commentator.RAHUL, "विश्व विजेता का ताज!"))),
        DialogueTemplate("CHP_06", listOf(CommentaryDialogue(Commentator.NEHA, "शानदार खेल, बने विश्व चैंपियन!"))),
        DialogueTemplate("CHP_07", listOf(CommentaryDialogue(Commentator.RAHUL, "वर्ल्ड कप पर किया कब्जा!"))),
        DialogueTemplate("CHP_08", listOf(CommentaryDialogue(Commentator.NEHA, "चैंपियन! चैंपियन! चैंपियन!"))),
        DialogueTemplate("CHP_09", listOf(CommentaryDialogue(Commentator.RAHUL, "विश्व कप की ऐतिहासिक जीत!"))),
        DialogueTemplate("CHP_10", listOf(CommentaryDialogue(Commentator.NEHA, "ट्रॉफी हवा में लहराई!"))),
        DialogueTemplate("CHP_11", listOf(CommentaryDialogue(Commentator.RAHUL, "चैंपियन बनने का सपना सच!"))),
        DialogueTemplate("CHP_12", listOf(CommentaryDialogue(Commentator.NEHA, "विश्व क्रिकेट का नया सरताज!"))),
        DialogueTemplate("CHP_13", listOf(CommentaryDialogue(Commentator.RAHUL, "वर्ल्ड कप विजेता का खिताब!"))),
        DialogueTemplate("CHP_14", listOf(CommentaryDialogue(Commentator.NEHA, "सुनहरे अक्षरों में जीत दर्ज!"))),
        DialogueTemplate("CHP_15", listOf(CommentaryDialogue(Commentator.RAHUL, "विश्व चैंपियन की दहाड़!"))),
        DialogueTemplate("CHP_16", listOf(CommentaryDialogue(Commentator.NEHA, "ट्रॉफी के साथ जश्न शुरू!"))),
        DialogueTemplate("CHP_17", listOf(CommentaryDialogue(Commentator.RAHUL, "गर्व से सिर ऊंचा, चैंपियन!"))),
        DialogueTemplate("CHP_18", listOf(CommentaryDialogue(Commentator.NEHA, "वर्ल्ड कप का ताज मिला!"))),
        DialogueTemplate("CHP_19", listOf(CommentaryDialogue(Commentator.RAHUL, "अविश्वसनीय जीत, बने चैंपियन!"))),
        DialogueTemplate("CHP_20", listOf(CommentaryDialogue(Commentator.NEHA, "विश्व विजेता का गौरव!"))),
        DialogueTemplate("CHP_21", listOf(CommentaryDialogue(Commentator.RAHUL, "आतिशबाजी और जश्न, चैंपियन!"))),
        DialogueTemplate("CHP_22", listOf(CommentaryDialogue(Commentator.NEHA, "वर्ल्ड कप जीत का परचम!"))),
        DialogueTemplate("CHP_23", listOf(CommentaryDialogue(Commentator.RAHUL, "चैंपियन बनने की बधाई!"))),
        DialogueTemplate("CHP_24", listOf(CommentaryDialogue(Commentator.NEHA, "ट्रॉफी हाथों में, विश्व विजेता!"))),
        DialogueTemplate("CHP_25", listOf(CommentaryDialogue(Commentator.RAHUL, "विश्व कप का असली सिकंदर!"))),
        DialogueTemplate("CHP_26", listOf(CommentaryDialogue(Commentator.NEHA, "चैंपियन का भव्य सम्मान!"))),
        DialogueTemplate("CHP_27", listOf(CommentaryDialogue(Commentator.RAHUL, "इतिहास में अमर हुई जीत!"))),
        DialogueTemplate("CHP_28", listOf(CommentaryDialogue(Commentator.NEHA, "विश्व कप की शानदार फतह!"))),
        DialogueTemplate("CHP_29", listOf(CommentaryDialogue(Commentator.RAHUL, "क्रिकेट का नया चैंपियन!"))),
        DialogueTemplate("CHP_30", listOf(CommentaryDialogue(Commentator.NEHA, "विश्व चैंपियन बनने का गौरव!"))),
        DialogueTemplate("CHP_31", listOf(CommentaryDialogue(Commentator.RAHUL, "वर्ल्ड कप की जीत मुबारक!"))),
        DialogueTemplate("CHP_32", listOf(CommentaryDialogue(Commentator.NEHA, "चैंपियन की विजय यात्रा!"))),
        DialogueTemplate("CHP_33", listOf(CommentaryDialogue(Commentator.RAHUL, "ट्रॉफी उठाकर नमन!"))),
        DialogueTemplate("CHP_34", listOf(CommentaryDialogue(Commentator.NEHA, "विश्व विजेता बने!"))),
        DialogueTemplate("CHP_35", listOf(CommentaryDialogue(Commentator.RAHUL, "शानदार चैंपियन!"))),
        DialogueTemplate("CHP_36", listOf(CommentaryDialogue(Commentator.NEHA, "विश्व कप जीत लिया है!"))),
        DialogueTemplate("CHP_37", listOf(CommentaryDialogue(Commentator.RAHUL, "चैंपियन का राज!"))),
        DialogueTemplate("CHP_38", listOf(CommentaryDialogue(Commentator.NEHA, "जीत का सबसे बड़ा दिन!"))),
        DialogueTemplate("CHP_39", listOf(CommentaryDialogue(Commentator.RAHUL, "विश्व कप की स्वर्णिम जीत!"))),
        DialogueTemplate("CHP_40", listOf(CommentaryDialogue(Commentator.NEHA, "चैंपियन! बधाई हो!")))
    )
}
