package com.example.domain.commentary.dialogues

import com.example.domain.commentary.CommentaryDialogue
import com.example.domain.commentary.Commentator

object WicketDialogues {

    // --- WICKET DIALOGUES (60 Short Variations, <= 1 sec) ---
    val WICKET_TEMPLATES: List<DialogueTemplate> = listOf(
        DialogueTemplate("WKT_01", listOf(CommentaryDialogue(Commentator.RAHUL, "ओह, विकेट!"))),
        DialogueTemplate("WKT_02", listOf(CommentaryDialogue(Commentator.NEHA, "क्लीन बोल्ड! आउट!"))),
        DialogueTemplate("WKT_03", listOf(CommentaryDialogue(Commentator.RAHUL, "ये तो बड़ा विकेट है!"))),
        DialogueTemplate("WKT_04", listOf(CommentaryDialogue(Commentator.NEHA, "आउट! गिल्लियां बिखर गईं!"))),
        DialogueTemplate("WKT_05", listOf(CommentaryDialogue(Commentator.RAHUL, "विकेट! बड़ा झटका!"))),
        DialogueTemplate("WKT_06", listOf(CommentaryDialogue(Commentator.NEHA, "कैच आउट! पारी समाप्त!"))),
        DialogueTemplate("WKT_07", listOf(CommentaryDialogue(Commentator.RAHUL, "गेंदबाज़ का कमाल, आउट!"))),
        DialogueTemplate("WKT_08", listOf(CommentaryDialogue(Commentator.NEHA, "अरे रे, विकेट गिरा!"))),
        DialogueTemplate("WKT_09", listOf(CommentaryDialogue(Commentator.RAHUL, "पवेलियन लौटना पड़ेगा!"))),
        DialogueTemplate("WKT_10", listOf(CommentaryDialogue(Commentator.NEHA, "शानदार गेंद, आउट!"))),
        DialogueTemplate("WKT_11", listOf(CommentaryDialogue(Commentator.RAHUL, "विकेट! जश्न का माहौल!"))),
        DialogueTemplate("WKT_12", listOf(CommentaryDialogue(Commentator.NEHA, "बड़ा झटका बल्लेबाज़ी टीम को!"))),
        DialogueTemplate("WKT_13", listOf(CommentaryDialogue(Commentator.RAHUL, "उंगली उठ गई! आउट!"))),
        DialogueTemplate("WKT_14", listOf(CommentaryDialogue(Commentator.NEHA, "दोनों का एक ही नंबर, आउट!"))),
        DialogueTemplate("WKT_15", listOf(CommentaryDialogue(Commentator.RAHUL, "गेंदबाज़ ने फंसाया, विकेट!"))),
        DialogueTemplate("WKT_16", listOf(CommentaryDialogue(Commentator.NEHA, "आउट! क्या गेंद थी!"))),
        DialogueTemplate("WKT_17", listOf(CommentaryDialogue(Commentator.RAHUL, "विकेट! बल्लेबाज़ सन्न!"))),
        DialogueTemplate("WKT_18", listOf(CommentaryDialogue(Commentator.NEHA, "पूरी तरह चकमा, आउट!"))),
        DialogueTemplate("WKT_19", listOf(CommentaryDialogue(Commentator.RAHUL, "खिलाड़ी आउट!"))),
        DialogueTemplate("WKT_20", listOf(CommentaryDialogue(Commentator.NEHA, "महत्वपूर्ण विकेट का पतन!"))),
        DialogueTemplate("WKT_21", listOf(CommentaryDialogue(Commentator.RAHUL, "विकेट! मैच पलटा!"))),
        DialogueTemplate("WKT_22", listOf(CommentaryDialogue(Commentator.NEHA, "आउट! सेट बल्लेबाज़ बाहर!"))),
        DialogueTemplate("WKT_23", listOf(CommentaryDialogue(Commentator.RAHUL, "गेंदबाज़ की जीत, आउट!"))),
        DialogueTemplate("WKT_24", listOf(CommentaryDialogue(Commentator.NEHA, "विकेट मिला फील्डिंग टीम को!"))),
        DialogueTemplate("WKT_25", listOf(CommentaryDialogue(Commentator.RAHUL, "आउट! ज़ोरदार अपील और आउट!"))),
        DialogueTemplate("WKT_26", listOf(CommentaryDialogue(Commentator.NEHA, "लापरवाही भारी, विकेट!"))),
        DialogueTemplate("WKT_27", listOf(CommentaryDialogue(Commentator.RAHUL, "आउट! डगआउट में सन्नाटा!"))),
        DialogueTemplate("WKT_28", listOf(CommentaryDialogue(Commentator.NEHA, "सटीक निशाना, आउट!"))),
        DialogueTemplate("WKT_29", listOf(CommentaryDialogue(Commentator.RAHUL, "विकेट! गेंदबाज़ का जादू!"))),
        DialogueTemplate("WKT_30", listOf(CommentaryDialogue(Commentator.NEHA, "गेंदबाज़ का दांव कामयाब, आउट!"))),
        DialogueTemplate("WKT_31", listOf(CommentaryDialogue(Commentator.RAHUL, "आउट! बल्लेबाज़ निराश!"))),
        DialogueTemplate("WKT_32", listOf(CommentaryDialogue(Commentator.NEHA, "विशाल विकेट गिरा!"))),
        DialogueTemplate("WKT_33", listOf(CommentaryDialogue(Commentator.RAHUL, "विकेट! तालियों की गड़गड़ाहट!"))),
        DialogueTemplate("WKT_34", listOf(CommentaryDialogue(Commentator.NEHA, "आउट! बल्लेबाज़ वापस!"))),
        DialogueTemplate("WKT_35", listOf(CommentaryDialogue(Commentator.RAHUL, "गेंदबाज़ की दहाड़, विकेट!"))),
        DialogueTemplate("WKT_36", listOf(CommentaryDialogue(Commentator.NEHA, "आउट! साझेदारी टूटी!"))),
        DialogueTemplate("WKT_37", listOf(CommentaryDialogue(Commentator.RAHUL, "बल्लेबाज़ का खेल खत्म!"))),
        DialogueTemplate("WKT_38", listOf(CommentaryDialogue(Commentator.NEHA, "विकेट! क्या मुकाबला है!"))),
        DialogueTemplate("WKT_39", listOf(CommentaryDialogue(Commentator.RAHUL, "आउट! सीधा जाल में फंसे!"))),
        DialogueTemplate("WKT_40", listOf(CommentaryDialogue(Commentator.NEHA, "गेंदबाज़ का मास्टरस्ट्रोक, आउट!"))),
        DialogueTemplate("WKT_41", listOf(CommentaryDialogue(Commentator.RAHUL, "विकेट! स्टंप्स हवा में!"))),
        DialogueTemplate("WKT_42", listOf(CommentaryDialogue(Commentator.NEHA, "आउट! खेल समाप्त बल्लेबाज़ का!"))),
        DialogueTemplate("WKT_43", listOf(CommentaryDialogue(Commentator.RAHUL, "विकेट! कप्तान गदगद!"))),
        DialogueTemplate("WKT_44", listOf(CommentaryDialogue(Commentator.NEHA, "आउट! बड़ा प्रहार फील्डिंग टीम का!"))),
        DialogueTemplate("WKT_45", listOf(CommentaryDialogue(Commentator.RAHUL, "विकेट! क्या टर्निंग पॉइंट है!"))),
        DialogueTemplate("WKT_46", listOf(CommentaryDialogue(Commentator.NEHA, "आउट! राहत की सांस गेंदबाज़ को!"))),
        DialogueTemplate("WKT_47", listOf(CommentaryDialogue(Commentator.RAHUL, "अविश्वसनीय विकेट!"))),
        DialogueTemplate("WKT_48", listOf(CommentaryDialogue(Commentator.NEHA, "आउट! पवेलियन की राह!"))),
        DialogueTemplate("WKT_49", listOf(CommentaryDialogue(Commentator.RAHUL, "विकेट का पतन!"))),
        DialogueTemplate("WKT_50", listOf(CommentaryDialogue(Commentator.NEHA, "आउट! बड़ा झटका लगा!"))),
        DialogueTemplate("WKT_51", listOf(CommentaryDialogue(Commentator.RAHUL, "गेंदबाज़ का वार, आउट!"))),
        DialogueTemplate("WKT_52", listOf(CommentaryDialogue(Commentator.NEHA, "विकेट! गेंदबाज़ चमका!"))),
        DialogueTemplate("WKT_53", listOf(CommentaryDialogue(Commentator.RAHUL, "आउट! अंपायर का इशारा!"))),
        DialogueTemplate("WKT_54", listOf(CommentaryDialogue(Commentator.NEHA, "विकेट! क्या गेंदबाज़ी है!"))),
        DialogueTemplate("WKT_55", listOf(CommentaryDialogue(Commentator.RAHUL, "आउट! बल्लेबाज़ ढेर!"))),
        DialogueTemplate("WKT_56", listOf(CommentaryDialogue(Commentator.NEHA, "विकेट! जबरदस्त जश्न!"))),
        DialogueTemplate("WKT_57", listOf(CommentaryDialogue(Commentator.RAHUL, "आउट! बोल्ड कर दिया!"))),
        DialogueTemplate("WKT_58", listOf(CommentaryDialogue(Commentator.NEHA, "विकेट! खेल बदल गया!"))),
        DialogueTemplate("WKT_59", listOf(CommentaryDialogue(Commentator.RAHUL, "आउट! शानदार कैच!"))),
        DialogueTemplate("WKT_60", listOf(CommentaryDialogue(Commentator.NEHA, "विकेट! गेंदबाज़ की जय!")))
    )
}
